name: Nginx Docker CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t nginx-html-app .

      - name: Verify Docker Image
        run: |
          docker images

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 --name mynginx nginx-html-app

      - name: Verify Running Container
        run: |
          docker ps

      - name: Test Application
        run: |
          curl http://localhost:8080

      - name: Cleanup Container
        run: |
          docker stop mynginx
          docker rm mynginx